name: ngsa Build

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - main

    paths:
    - 'NewApp/ngsa-csharp/**'
    - '.github/workflows/new.yaml'

  push:
    branches:
      - main

    paths:
    - 'NewApp/ngsa-csharp/**'
    - '.github/workflows/new.yaml'

    tags:
      - v*

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      # copy the config value to environment variables
      # do not copy the actual secrets!

      APP_REPO: retaildevcrew/ngsa-app
      DS_REPO: retaildevcrew/ngsa-dataservice
      LR_REPO: retaildevcrew/loderunner

      # These are used in if: conditions
      DOCKER_SET: false
      COSMOS_SET: false
      BUILD: true

    steps:
    - uses: actions/checkout@v2

    - name: Set conditions
      run: |
        # check that all Docker secrets are set
        if [[ "${{ secrets.DOCKER_PAT }}" != "" && "${{ secrets.NGSA_REPO }}" != "" && "${{ secrets.DOCKER_USER }}" != "" ]];
        then
          echo "DOCKER_SET=true" >> $GITHUB_ENV
        fi
        
        if [[ "${{ secrets.CosmosUrl }}" != "" && "${{ secrets.CosmosKey }}" != "" ]];
        then
          echo '${{ secrets.CosmosUrl }}' > src/ngsa/app/secrets/CosmosUrl
          echo '${{ secrets.CosmosKey }}' > src/ngsa/app/secrets/CosmosKey
          echo "COSMOS_SET=true" >> $GITHUB_ENV
        fi

